WonderWeb/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Index
    path('', views.index, name='index'),

    # Detalles de una pregunta
    path('<int:pregunta_id>/', views.details, name='details'),

    # Las respuestas a una pregunta
    path('<int:pregunta_id>/results/', views.result, name='result'),

    # Los votos a una respuesta
    path('<int:pregunta_id>/vote/', views.vote, name='vote'),





    # HOME
    path('home/', views.home, name='home'),

    # EntornoVirtual
    path('entornoVirtual/', views.entornoVirtual, name='entornoVirtual'),

    # Contactanos
    path('contactanos/', views.contactanos, name='contactanos'),

    # Registro de Ususario
    path('registro/', views.registro, name='registro'),

    # Proyectos
    path('proyectos/', views.proyectos, name='proyectos'),

]

WonderWeb_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from WonderWeb.views import *

import WonderWeb

urlpatterns = [
    path('', home, name='home'),
    path('entornoVirtual/', entornoVirtual, name='entornoVirtual'),
    path('contactanos/', contactanos, name='contactanos'),
    path('registro/', registro, name='registro'),
    path('proyectos/', proyectos, name='proyectos'),
    path('admin/', admin.site.urls),
    path('WonderWeb/', include('WonderWeb.urls'))
]

WonderWeb/models.py
from django.db import models

class Preguntas(models.Model):
    pregunta = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.pregunta


class Respuestas(models.Model):
    preguntaFK = models.ForeignKey(Preguntas, on_delete=models.CASCADE)
    respuesta = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    def __str__(self):
        return self.respuesta

WonderWeb/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from WonderWeb.models import Preguntas


def index(request):
     preguntas = Preguntas.objects.all()
     respuesta = ''

     for pregunta in preguntas:
         respuesta += pregunta.pregunta + '<br>'

     return render(request, "WonderWeb/Tutorial/index.html", {
         "preguntas" : preguntas
     })

def details(request, pregunta_id):
    pregunta = Preguntas.objects.get(pk=pregunta_id)
    return render(request, "WonderWeb/Tutorial/details.html", {
        "pregunta" : pregunta
    })

def home(request):
    return render(request, "WonderWeb/home_HTML.html")

def contactanos(request):
    return render(request, "WonderWeb/contactanos_HTML.html")

def entornoVirtual(request):
    return render(request, "WonderWeb/entornoVirtual_HTML.html")

def registro(request):
    return render(request, "WonderWeb/registro_HTML.html")

def proyectos(request):
    return render(request, "WonderWeb/proyectos_HTML.html")


def result(request, pregunta_id):
    return HttpResponse('Estás mirando las respuestas de la pregunta %s.' % pregunta_id)

def vote(request, pregunta_id):
    return HttpResponse('Estás mirando los votos de la pregunta %s.' % pregunta_id)


# preguntas = Preguntas.objects.all()
#     respuesta = ''
#
#     for pregunta in preguntas:
#         respuesta += pregunta.pregunta + '<br>'

WonderWeb/templates/WonderWeb/Tutorial/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Preguntas</title>
</head>
<body>

<h1>Contenido de la Página, puto</h1>

<div id="app" class="container">
    {% block content %}
    {% endblock %}
</div>


</body>
</html>

WonderWeb/templates/WonderWeb/Tutorial/details.html
{% extends 'WonderWeb/Tutorial/base.html' %}

{% block content %}
    <h2>{{ pregunta.pregunta }}</h2>
    <ul>
        {% for respuesta in pregunta.respuestas_set.all %}
            <li>{{ respuesta.respuesta }}</li>
        {% endfor %}
    </ul>
{% endblock %}

WonderWeb/templates/WonderWeb/Tutorial/index.html
{% extends 'WonderWeb/Tutorial/base.html' %}

{% block content %}
    <h2>Preguntas</h2>
    {% if preguntas %}
        <ul>
            {% for pregunta in preguntas %}
                <li><a href="{% url 'details' pregunta.id %}">{{ pregunta.pregunta }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No hay preguntas</p>
    {% endif %}
{% endblock %}

WonderWeb/templates/WonderWeb/Utils/wonderTemplate_HTML.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    {% block linkCSS %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/wonder_CSS.css' %}">
    <link rel="shortcut icon" href="{% static 'imagenes/faviconAux.ico' %}"/>

    <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css /">
    <link href="https://fonts.googleapis.com/css?family=Supermercado+One&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

    <script src="https://unpkg.com/htmx.org@1.6.1"></script>




    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
        integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg=="
        crossorigin="anonymous" />



</head>
<body class="templateBody">


<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->


<!-- INICIO - HEADER Nº1 -->
<div class="header" id="divHeaderID" hx-boost="true">
    <div class="imagen_div">
        <a href="{% url 'home' %}">
            <img src="{% static 'imagenes/logoWonder.png' %}" alt="logo Wonder" id="imagen_Header">
        </a>
    </div>
    <div class="headerSeparator"></div>
    <div id="login">
        <!-- INICIO Boton de Login -->
        <button onclick="document.getElementById('id01').style.display='block'" style="width:auto;" id="login_B">Login
        </button>
        <div id="id01" class="modal">
            <form class="modal-content animate" action="/action" method="post">
                <div class="imgcontainer">
                    <span onclick="document.getElementById('id01').style.display='none'" class="close"
                          title="Close Modal">&times;</span>
                </div>
                <div class="container">
                    <div id="wr_log">
                        <div id="user">
                            <label for="uname"><b id="texto_log1">Usuari</b></label>
                            <input type="text" placeholder="Username" name="uname" required id="uname">
                        </div>
                        <div id="mid_log"></div>
                        <div id="pass">
                            <label for="psw"><b id="texto_log2">Contrasenya</b></label>
                            <input type="password" placeholder="Enter Password" name="psw" required id="psw">
                        </div>
                    </div>
                    <br>
                    <button type="submit" id="login_B2">LOGIN</button>
                    <label>
                        <input type="checkbox" checked="checked" name="remember"> Recordam?
                    </label>
                    <br><br>
                    <span class="registerText" hx-boost="false">
                            No estas registrat? <br>
                            Fes-ho <a href="{% url 'registro' %}">aquí</a>
                    </span>
                </div>
                <div class="container" style="background-color:#f1f1f1">
                    <button type="button" onclick="document.getElementById('id01').style.display='none'"
                            class="cancelbtn">CANCELAR
                    </button>
                    <span class="psw">Has olvidat la <a href="#">contrasenya?</a></span>
                </div>
            </form>
        </div>
        <script>
            var modal = document.getElementById('id01');
            window.onclick = function (event) {
                if (event.target === modal) {
                    modal.style.display = "none";
                }
            }
        </script>
        <!-- FINAL Boton de Login -->
    </div>
</div>
<!-- FINAL - HEADER Nº1 -->


<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->


<!-- INICIO - HEADER Nº2 -->
<div id="div_headerT">
    <div class="margenes_head1"></div>


    <!-- INICIO - HOME -->
    <div id="inicio">
        <a href="{% url 'home' %}" class="listado_header">INICI</a>
    </div>
    <!-- FINAL - HOME -->


    <div class="margenes_head2"></div>


    <!-- INICIO - NECESITAS AYUDA -->
    <div id="necesitasAyuda" class="dropdown">
        <a href="javascript:void(0)" class="dropbtn listado_header">NECESSITES AJUDA?</a>
        <div class="dropdown-content">
            <a href="#">Link 1</a>
            <a href="#">Link 2</a>
            <a href="#">Link 3</a>
        </div>
    </div>
    <!-- FINAL - NECESITAS AYUDA -->


    <div class="margenes_head2"></div>


    <!-- INICIO - PROYECTOS -->
    <div id="proyectos">
        <a href="{% url 'proyectos' %}" class="listado_header">PROJECTES</a>
    </div>
    <!-- FINAL - PROYECTOS -->


    <div class="margenes_head2"></div>


    <!-- INICIO - ENTORNO VIRTUAL -->
    <div id="entornoVirtual">
        <a href="{% url 'entornoVirtual' %}" class="listado_header">ENTORN VIRTUAL</a>
    </div>
    <!-- FINAL - ENTORNO VIRTUAL -->


    <div class="margenes_head2"></div>


    <!-- INICIO - CONTACTANOS -->
    <div id="contactanos">
        <a href="{% url 'contactanos' %}" class="listado_header">CONTACTE</a>
    </div>
    <!-- FINAL - CONTACTANOS -->


    <div class="margenes_head1"></div>
</div>
<!-- FINAL - HEADER Nº2 -->


<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->


<!-- INICIO - CONTENIDO -->
<div class="flexPagina">
    <div class="margenLateral"></div>
    <div class="centroPagina">
        {% block contenido %}{% endblock %}
    </div>
    <div class="margenLateral"></div>
</div>
<!-- FINAL - CONTENIDO -->

<br><br><br><br>


<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->


<!-- INICIO - BANNER AD -->
<br><br>
<div class="BannerAD">
    <span>Full Banner AD</span>
</div>
<!-- FINAL - BANNER AD -->

<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->


<!-- INICIO - FOOTER 1 -->
<div class="footer1" hx-boost="true">
    <div class="footer1_margin"></div>


    <!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->


    <div class="mapaGoogle">
        <h1 class="titleFooter">Contacta amb Nosaltres</h1>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2992.8857678682184!2d2.2010485154261477!3d41.39828707926322!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12a4a315252f0f33%3A0x7c28ad8c59d3778e!2sInstitut%20Poblenou%20ECAIB!5e0!3m2!1sca!2ses!4v1639670153661!5m2!1sca!2ses"
                style="border:0;" allowfullscreen=""></iframe>
        <br>
        <div class="dividedFooter">
            <div class="phone">
                <img src="{% static 'imagenes/phone.png' %}" alt="Alaverga" class="imgPhone">
            </div>
            <div class="textPhone">
                932 25 38 12 <br>
                Dilluns - Divendres <br>
                09:00 - 21:00 <br>
                SEGUEIX-NOS
            </div>
        </div>

    </div>


    <!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->


    <div class="sendEmail">
        <h1 class="titleFooter">Envia'ns un Correu</h1>
        <form action="">
            <input type="text" placeholder="El teu nom..."> <br> <br>
            <input type="text" placeholder="El teu correu..."> <br> <br>
            <textarea name="" id="" cols="30" rows="10" placeholder="El teu missatge aquí..."></textarea> <br><br>
            <button type="submit" class="btnEmail">Enviar</button>
        </form>
    </div>


    <!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->


    <div class="footer1_margin"></div>
</div>
<!-- FINAL - FOOTER 1 -->



<!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->



<!-- INICIO - FOOTER 2 -->
<div class="footer2" hx-boost="true">
    <div class="marginFoot2"></div>


    <div class="flex-ft2-1">
        <a href="">Avís Legal</a>
    </div>

    <div class="flex-ft2-2">
        <a href="">Política de privacitat</a>
    </div>

    <div class="flex-ft2-2">
        <a href="">Política de cookies</a>
    </div>

    <div class="flex-ft2-1">
        <a href="">Contacte</a>
    </div>

    <div class="flex-ft2-1">
        <a href="">Sitemap</a>
    </div>

    <div class="marginFoot2"></div>
</div>
<div class="endText">
    <span>CIF X-XXXXXX-X Registre de Fundacions de competència estatal amb núm. de registre XXX</span>
</div>
<!-- FINAL - FOOTER 2 -->


</body>
</html>

WonderWeb/templates/WonderWeb/contactanos_HTML.html
{% extends 'WonderWeb/Utils/wonderTemplate_HTML.html' %}

{% load static %}

{% block title %} Inicio - Wonder {% endblock %}

{% block linkCSS %}<link rel="stylesheet" type="text/css" href="{% static 'CSS/contactanos_CSS.css' %}">{% endblock %}

{% block contenido %}

    <br><br><br>
    <h1 class="tituloGeneral">WONDER</h1>
    <br>
    <h2 class="subtituloGeneral">CONTACTANOS</h2>

{% endblock %}

WonderWeb/templates/WonderWeb/home_HTML.html
{% extends 'WonderWeb/Utils/wonderTemplate_HTML.html' %}

{% load static %}

{% block title %} Inicio - Wonder {% endblock %}

{% block linkCSS %}<link rel="stylesheet" type="text/css" href="{% static 'CSS/home_CSS.css' %}">{% endblock %}

{% block contenido %}



            <!-- INICIO - SLIDER -->
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'imagenes/slider/imagenSlider_1.jpeg' %}" class="d-block w-100" alt="..."
                             class="carrousel">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'imagenes/slider/imagenSlider_2.jpeg' %}" class="d-block w-100" alt="..."
                             class="carrousel">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'imagenes/slider/imagenSlider_3.jpeg' %}" class="d-block w-100" alt="..."
                             class="carrousel">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <!-- FINAL - SLIDER -->



            <!-- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ -->



            <!-- INICIO - TEXTOS CENTRADOS -->
            <div class="contenedorTextosCentrados">
                <div class="contenedorTexto1">
                    <p class="textoCentrado">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy
                        text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has
                        survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was
                        popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
                        publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                    </p>
                </div>
                <div class="marginTextoCentrado"></div>
                <div class="contenedorTexto1">
                    <p class="textoCentrado">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy
                        text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has
                        survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was
                        popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
                        publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                    </p>
                </div>
                <div class="marginTextoCentrado"></div>
                <div class="contenedorTexto1">
                    <p class="textoCentrado">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy
                        text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has
                        survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was
                        popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
                        publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                    </p>
                </div>
            </div>
            <!-- INICIO - TEXTOS CENTRADOS -->

{% endblock %}

WonderWeb/templates/WonderWeb/proyectos_HTML.html
{% extends 'WonderWeb/Utils/wonderTemplate_HTML.html' %}

{% load static %}

{% block title %} Proyectos - Wonder {% endblock %}

{% block linkCSS %}<link rel="stylesheet" type="text/css" href="{% static 'CSS/proyectos_CSS.css' %}">{% endblock %}

{% block contenido %}

    <br><br><br>
    <h1 class="tituloGeneral">WONDER</h1>
    <br>
    <h2 class="subtituloGeneral">PROJECTES</h2>

{% endblock %}